name: Deploy to AWS EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Copy project to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "mkdir -p ${{ secrets.EC2_TARGETDIR }}"
          rsync -az --delete --exclude=node_modules --exclude=".git*" ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_TARGETDIR }}/


      - name: Install & Restart App
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
            cd ${{ secrets.EC2_TARGETDIR }} &&
            npm install &&
            npm run build &&
            pm2 stop myapp || true &&
            pm2 start npm --name myapp -- start &&
            pm2 save
          "
